spring.application.name=lapmart-email-service

server.port=8080

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chathuramalith94@gmail.com
spring.mail.password=ygehdfafsafadsfdsafcenwultadfsdfsdfsdfdlubp353gdfgdfwgfffdfdghfdafhdasfh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
